chore: shellcheck on ./test

diff --git a/test b/test
--- a/test
+++ b/test
@@ -11,45 +11,48 @@
 #
 set -e
 
-source $(dirname $0)/scripts/readlinkdashf.sh
-BASEDIR=$(readlinkdashf $(dirname $0))
+source "$(dirname "$0")"/scripts/readlinkdashf.sh
+BASEDIR=$(readlinkdashf "$(dirname "$0")")
 BINDIR=${BASEDIR}/bin
 
-if [ $PWD != $BASEDIR ]; then
-	cd $BASEDIR
+if [ "$PWD" != "$BASEDIR" ]; then
+	cd "$BASEDIR"
 fi
 
 ORG_PATH="github.com/sorintlab"
 REPO_PATH="${ORG_PATH}/stolon"
 
-# test all packages excluding integration tests
-IGNORE_PKGS="(vendor/|tests/integration)"
-PACKAGES=$(find . -name \*_test.go | while read -r a; do dirname "$a"; done | sort | uniq | grep -vE "$IGNORE_PKGS" | sed "s|\./||g")
-
-# prepend REPO_PATH to each local package
-split=$PACKAGES
-PACKAGES=""
-for a in $split; do PACKAGES="$PACKAGES ${REPO_PATH}/${a}"; done
-
 echo "Running tests..."
 
 COVER=${COVER:-"-cover"}
 
+function go_files_without_license_info() {
+	find . -type f -iname '*.go' ! -path './vendor/*' | while read -r file; do
+		head -n3 "${file}" | grep -Eq "(Copyright|generated|GENERATED)" || echo -e "  ${file}"
+	done
+}
+
 echo "Checking for license header..."
-licRes=$(for file in $(find . -type f -iname '*.go' ! -path './vendor/*'); do
-	head -n3 "${file}" | grep -Eq "(Copyright|generated|GENERATED)" || echo -e "  ${file}"
-done)
-if [ -n "${licRes}" ]; then
-	echo -e "license header checking failed:\n${licRes}"
+IFS=$'\n' read -r -d '' -a licRes < <(go_files_without_license_info) || true
+if ((${#licRes[@]})); then
+	echo -e "license header checking failed:\n${licRes[*]}"
 	exit 255
 fi
 
-echo "Running tests"
-go test -timeout 3m ${COVER} $@ ${PACKAGES} ${RACE}
+echo "Running go test"
+# test all packages excluding integration tests
+IGNORE_PKGS="(vendor/|tests/integration)"
+
+function find_packages() {
+	find "." -name \*_test.go | while read -r a; do dirname "$a"; done | sort | uniq | grep -vE "$IGNORE_PKGS" | sed "s|^\.|${REPO_PATH}|g"
+}
+IFS=$'\n' read -r -d '' -a PACKAGES < <(find_packages) || true
+
+go test -timeout 3m "${COVER}" "$@" "${PACKAGES[@]}" "${RACE[@]}"
 
 if [ -n "$INTEGRATION" ]; then
 	echo "Running integration tests..."
-	if [ -z ${STOLON_TEST_STORE_BACKEND} ]; then
+	if [ -z "${STOLON_TEST_STORE_BACKEND}" ]; then
 		echo "STOLON_TEST_STORE_BACKEND env var needs to be defined (etcd or consul)"
 		exit 1
 	fi
@@ -57,9 +60,9 @@ if [ -n "$INTEGRATION" ]; then
 	export STSENTINEL_BIN=${BINDIR}/stolon-sentinel
 	export STPROXY_BIN=${BINDIR}/stolon-proxy
 	export STCTL_BIN=${BINDIR}/stolonctl
-	if [ "${STOLON_TEST_STORE_BACKEND}" == "etcd" -o "${STOLON_TEST_STORE_BACKEND}" == "etcdv2" -o "${STOLON_TEST_STORE_BACKEND}" == "etcdv3" ]; then
-		if [ -z ${ETCD_BIN} ]; then
-			if [ -z $(which etcd) ]; then
+	if [ "${STOLON_TEST_STORE_BACKEND}" == "etcd" ] || [ "${STOLON_TEST_STORE_BACKEND}" == "etcdv2" ] || [ "${STOLON_TEST_STORE_BACKEND}" == "etcdv3" ]; then
+		if [ -z "${ETCD_BIN}" ]; then
+			if [ -z "$(which etcd)" ]; then
 				echo "cannot find etcd in PATH and ETCD_BIN environment variable not defined"
 				exit 1
 			fi
@@ -68,8 +71,8 @@ if [ -n "$INTEGRATION" ]; then
 		echo "using etcd from $ETCD_BIN"
 		export ETCD_BIN
 	elif [ "${STOLON_TEST_STORE_BACKEND}" == "consul" ]; then
-		if [ -z ${CONSUL_BIN} ]; then
-			if [ -z $(which consul) ]; then
+		if [ -z "${CONSUL_BIN}" ]; then
+			if [ -z "$(which consul)" ]; then
 				echo "cannot find consul in PATH and CONSUL_BIN environment variable not defined"
 				exit 1
 			fi
@@ -83,7 +86,7 @@ if [ -n "$INTEGRATION" ]; then
 	fi
 
 	[ -z "$PARALLEL" ] && PARALLEL=4
-	go test -timeout 20m $@ -v -count 1 -parallel ${PARALLEL} ${REPO_PATH}/tests/integration
+	go test -timeout 20m "$@" -v -count 1 -parallel "${PARALLEL}" "${REPO_PATH}"/tests/integration
 fi
 
 echo "Success"
