Enabling ci

diff --git a/.github/workflows/ci-run-on-pr.yaml b/.github/workflows/ci-run-on-pr.yaml
--- a/.github/workflows/ci-run-on-pr.yaml
+++ b/.github/workflows/ci-run-on-pr.yaml
@@ -6,6 +6,10 @@ on:
 env:
   # Golang version to use across CI steps
   GOLANG_VERSION: '1.25' # As we have go toolchain 1.25 specified in go.mod
+  DOWNLOAD_URL: https://github.com/etcd-io/etcd/releases/download
+  ETCD_VER: v3.6.8
+  ETCD_PATH: /usr/local/bin/
+  ETCD_BIN: /usr/local/bin/etcd
 
 permissions:
   contents: read
@@ -266,6 +270,12 @@ jobs:
         with:
           go-version: ${{ env.GOLANG_VERSION }}
 
+      - name: installe etcd
+        run: |
+          curl -L ${DOWNLOAD_URL}/${ETCD_VER}/etcd-${ETCD_VER}-linux-amd64.tar.gz -o /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz
+          tar xzvf /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz -C "${ETCD_PATH}" --strip-components=1 --no-same-owner
+          rm -f /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz
+
       - name: Download keeper artifact
         uses: actions/download-artifact@v4
         with:
@@ -293,3 +303,30 @@ jobs:
         run: make e2e-test
         env:
           PGVERSION: ${{ matrix.pgversion }}
+          STOLON_TEST_STORE_BACKEND: etcdv3
+
+  license-header-test:
+    name: License header test
+    runs-on: ubuntu-22.04
+    needs:
+      - codechanges
+    if: ${{ (needs.codechanges.outputs.backend == 'true' || needs.codechanges.outputs.ci == 'true') && github.event.pull_request.draft == false}}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@8410ad0602e1e429cee44a835ae9f77f654a6694 # v4.0.0
+      - name: Test
+        run: |
+          function go_files_without_license_info() {
+          	find . -type f -iname '*.go' ! -path './vendor/*' ! -path './tests/*' ! -name '*_test.go' | while read -r file; do
+          		head -n3 "${file}" | grep -Eq "(Copyright|generated|GENERATED)" || echo -e "  ${file}"
+          	done
+          }
+          
+          echo "Checking for license header..."
+          IFS=$'\n' read -r -d '' -a licRes < <(go_files_without_license_info) || true
+          if ((${#licRes[@]})); then
+          	echo -e "license header checking failed:\n${licRes[*]}"
+          	exit 255
+          fi
+
+          echo Success
